defaults: &defaults
  gmail_username: 'noreply@ikalogs.ru'
  gmail_password: 'q=p+dqKWiy6Z'


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  gmail_username: 'noreply@ikalogs.ru'
  gmail_password: 'q=p+dqKWiy6Z'