defaults: &defaults
  gmail_username: 'username@gmail.com'
  gmail_password: 'Gmail password'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  gmail_username: 'username@gmail.com'
  gmail_password: 'Gmail password'